spring.application.name=bai2

# Ket noi MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/bai5_qlsp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# JPA
spring.jpa.hibernate.ddl-auto=update